services:
  petshop-api:
    container_name: petshop-api
    restart: always
    image: node:20.10.0
    ports:
      - 4008:3000
    volumes:
      - ./:/usr/src/petshop
    working_dir: /usr/src/petshop

    networks:
      - monorepo-network

    #FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  petshop-batch:
    container_name: petshop-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4009:3001
    volumes:
      - ./:/usr/src/petshop
    working_dir: /usr/src/petshop

    networks:
      - monorepo-network

    #FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# petshop-next:   localhost:4007 => container:3000
# petshop-api:    localhost:4008 => container:3001
# petshop-batch:  localhost:4009 => container:3003

# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
# docker compose stop && docker compose rm -f
