services:
  petshop-api:
    container_name: petshop-api
    restart: always
    image: node:20.10.0
    ports:
      - 5001:6007
    volumes:
      - ./:/usr/src/petshop
    working_dir: /usr/src/petshop

    networks:
      - monorepo-network

    #FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  petshop-batch:
    container_name: petshop-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 5002:6008
    volumes:
      - ./:/usr/src/petshop
    working_dir: /usr/src/petshop

    networks:
      - monorepo-network

    #FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# petshop-next:   localhost:5000 => container:6000
# petshop-api:    localhost:5001 => container:6007
# petshop-batch:  localhost:5002 => container:6008

# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
# docker compose stop && docker compose rm -f
